version: '3'
services:
  db:
    image: postgres
    volumes:
      - 'data:/var/lib/postgresql/data'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/colabore
    ports:
      - "3000:3000"
    depends_on:
      - 'db'
volumes:
  data:
