version: '3'
services:
  db:
    image: postgres
    volumes:
      - 'data:/var/lib/postgresql/data'
    ports:
      - "5432"
  web:
    build: .
    command: bash start.sh
    volumes:
      - .:/colabore
    volumes:
      - box:/box
    ports:
      - "3000:3000"
    depends_on:
      - 'db'

  box:
    image: busybox
    volumes:
      - /box
volumes:
  data:
  box:
