development: &default
  adapter: postgresql
  encoding: unicode
  database: colabore_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: colabore_test

production:
  <<: *default
  database: colabore_production
  username: colabore
  password: <%= ENV['COLABORE_DATABASE_PASSWORD'] %>
