# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9b8c85769df49fb1b47c94753c889308dd46fe38e1bd0b71c9c2fa68a6315b762588a469550f3e6930a87be9683911733ce8f0ca17755189540bd691c229f6d

test:
  secret_key_base: 40719b2dcd6eacd493d66fd73c5c03f20b10a69f0d11bd8939dd579799c2cce57f84e2f04c55b741b97a77c6ab4eafb532383c989fcb982e39a963cf8ee46e86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
